import type { CyberPassField, CyberPassControl, ScanResult, ExcelRequirement, FillOptions, FillResult } from '../shared/types';
import { normalizeRequirementId } from '../excel/normalizer';

const REQ_RE=/\b(?:Requirement|Req)\s*#?\s*([0-9]+(?:\.[0-9]+)*)\b/i;
function clean(s:string){return s.replace(/\s+/g,' ').trim();}
function controlInfo(el: HTMLElement): CyberPassControl { const x=el as HTMLInputElement; return {tag:el.tagName.toLowerCase(),type:x.type,name:x.name,id:el.id,ariaLabel:el.getAttribute('aria-label')||undefined,value:readValue(el),selectorHint:el.id?`#${CSS.escape(el.id)}`:undefined}; }
export function readValue(el: HTMLElement):string { const x=el as HTMLInputElement; if(el instanceof HTMLSelectElement)return [...el.selectedOptions].map(o=>o.text).join(', '); if(el.isContentEditable)return el.textContent||''; return x.value||''; }
function setNativeValue(el: HTMLElement,value:string){
  if(el instanceof HTMLSelectElement){const option=[...el.options].find(o=>o.text.trim()===value.trim()||o.value===value); if(option)el.value=option.value; else {const fallback=[...el.options].find(o=>o.text.toLowerCase().includes(value.toLowerCase())); if(fallback)el.value=fallback.value;} el.dispatchEvent(new Event('change',{bubbles:true})); return;}
  if(el.isContentEditable){el.textContent=value;el.dispatchEvent(new InputEvent('input',{bubbles:true,inputType:'insertText',data:value}));el.dispatchEvent(new Event('change',{bubbles:true}));return;}
  const proto=el instanceof HTMLTextAreaElement?HTMLTextAreaElement.prototype:HTMLInputElement.prototype; const setter=Object.getOwnPropertyDescriptor(proto,'value')?.set; setter?.call(el,value); el.dispatchEvent(new Event('input',{bubbles:true}));el.dispatchEvent(new Event('change',{bubbles:true}));el.dispatchEvent(new Event('blur',{bubbles:true}));
}
function requirementContainer(node:HTMLElement):HTMLElement { return node.closest('.input-node-view-builder-container') as HTMLElement || node.parentElement || node; }
function findFields(): ScanResult {
  const fields:CyberPassField[]=[]; const seen=new Set<string>();
  const candidates=[...document.querySelectorAll<HTMLElement>('.input-node-view-builder-header, [data-requirement], h1,h2,h3,h4,h5,h6')];
  for(const node of candidates){const txt=clean(node.textContent||''); const m=txt.match(REQ_RE); if(!m)continue; const id=normalizeRequirementId(m[1]); if(!id||seen.has(id))continue; const container=requirementContainer(node); const controls=[...container.querySelectorAll<HTMLElement>('textarea, input:not([type="hidden"]):not([type="file"]), select, [contenteditable="true"]')]; if(!controls.length)continue; seen.add(id); const label=clean((node.nextElementSibling?.textContent||'').slice(0,160)); fields.push({requirementId:id,label,containerText:clean(container.textContent||'').slice(0,500),controls:controls.map(controlInfo)}); }
  return {fields,debug:fields.map(f=>({requirementId:f.requirementId,text:f.containerText,controls:f.controls.map(({tag,type,name,id,ariaLabel})=>({tag,type,name,id,ariaLabel}))}))};
}
function elementForField(field:CyberPassField):HTMLElement|null { const ordered=[...field.controls].sort((a,b)=>({textarea:0,contenteditable:1,select:2,input:3}[a.tag]??4)-({textarea:0,contenteditable:1,select:2,input:3}[b.tag]??4)); const c=ordered[0]; if(!c)return null; if(c.id)return document.getElementById(c.id); if(c.selectorHint){try{return document.querySelector(c.selectorHint)}catch{}} return null; }
function mark(el:HTMLElement,kind:'ok'|'warn'|'fail'){const old=el.style.outline; el.style.outline=kind==='ok'?'3px solid #2e9d62':kind==='warn'?'3px solid #d97706':'3px solid #dc2626'; el.style.outlineOffset='2px'; setTimeout(()=>{el.style.outline=old;el.style.outlineOffset='';},3500);}
export function scanPage(){return findFields();}
export function preview(requirements:ExcelRequirement[]){const scan=findFields(); const byId=new Map(requirements.map(r=>[r.requirementId,r])); const rows=[] as any[]; for(const f of scan.fields){const r=byId.get(f.requirementId); const el=elementForField(f); const current=el?readValue(el):''; if(r){const status=!r.value?'empty':current&&current.trim()!==r.value.trim()?'mismatch':'matched'; rows.push({requirementId:f.requirementId,excel:r,cyberPass:f,status,currentValue:current,reason:status==='mismatch'?'Existing value differs from workbook':''}); if(status==='mismatch'&&el)mark(el,'warn');} else rows.push({requirementId:f.requirementId,cyberPass:f,status:'unmatched-page',currentValue:current}); }
  for(const r of requirements)if(!scan.fields.some(f=>f.requirementId===r.requirementId))rows.push({requirementId:r.requirementId,excel:r,status:'unmatched-excel'});
  return {scan,rows}; }
export function fill(requirements:ExcelRequirement[],options:FillOptions):FillResult {const scan=findFields();const byId=new Map(requirements.map(r=>[r.requirementId,r]));const out:FillResult={filled:0,skipped:0,failed:0,mismatches:0,errors:[]}; for(const f of scan.fields){const r=byId.get(f.requirementId);if(!r)continue;const el=elementForField(f);if(!el){out.failed++;out.errors.push(`${f.requirementId}: editable control not found`);continue;}const current=readValue(el);if(!r.value){out.skipped++;continue;}if(current.trim()&&!options.replaceExisting){if(current.trim()!==r.value.trim()){out.mismatches++;mark(el,'warn');}out.skipped++;continue;}try{setNativeValue(el,r.value);mark(el,'ok');out.filled++;}catch(e){out.failed++;mark(el,'fail');out.errors.push(`${f.requirementId}: ${String(e)}`);}} return out;}
export function installHelpers(requirements:ExcelRequirement[]){const byId=new Map(requirements.map(r=>[r.requirementId,r])); document.querySelectorAll('[data-cyberpass-helper]').forEach(e=>e.remove()); for(const f of findFields().fields){const r=byId.get(f.requirementId);if(!r)continue;const el=elementForField(f);if(!el)continue;const btn=document.createElement('button');btn.type='button';btn.textContent='Fill from Excel';btn.dataset.cyberpassHelper='1';btn.style.cssText='margin:4px 0;padding:3px 7px;font:11px system-ui;cursor:pointer;background:#eef6ff;border:1px solid #6aa7df;border-radius:4px;';btn.addEventListener('click',()=>{const current=readValue(el);if(current&&current.trim()!==r.value.trim()&&!confirm(`Requirement ${f.requirementId} already has content. Replace it?`))return;setNativeValue(el,r.value);mark(el,'ok');btn.textContent='Filled ✓';}); el.parentElement?.insertBefore(btn,el);}}
export function debugDom(){return findFields().debug;}
